version: '3'
services:
  app:
    container_name: app
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    environment:
      - MONGODB_URI=mongodb://mongo:27017/app
    env_file: ".env.local"

  mongo:
    container_name: mongo
    image: mongo:latest
    volumes:
      - mongo_data:/data/db
    env_file: ".env.local"

  cloudflared:
    container_name: cloudflared
    network_mode: "host"
    image: cloudflared:latest
    command: tunnel --no-autoupdate run --token ${CLOUDFLARE_TUNNEL_TOKEN}

volumes:
  mongo_data:
    driver: local
