import './global.scss';
import { ClerkProvider } from '@clerk/nextjs';
import NavigationBar from '../components/NavigationBar';

export const metadata = {
  title: 'Welcome to web',
  description: 'Generated by create-nx-workspace',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <ClerkProvider>
    <html lang="en">
      <body>
      <div className={"d-flex flex-column vh-100"}>
        <NavigationBar />
      {children}
      </div>
      </body>
    </html>
    </ClerkProvider>
  );
}
